### ISSUE TITLE
TypeError: typechain_1.glob is not a function on compile

### ISSUE THREAD

**Issue by reilgun** [dethcrypto/TypeChain#466]
I'm using TypeChain with Hardhat and Typescript on node v16.9.1
I configured it as recommended here for hardhat/ethers 
And I am getting this error on compile:
```
TypeError: typechain_1.glob is not a function
    at SimpleTaskDefinition.action (D:\projects\projectA\node_modules\@typechain\hardhat\src\index.ts:63:22)
    at Environment._runTaskDefinition (D:\projects\projectA\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:35)
    at OverriddenTaskDefinition._action (D:\projects\projectA\node_modules\@typechain\hardhat\src\index.ts:31:11)
    at async Environment._runTaskDefinition (D:\projects\projectA\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at async Environment.run (D:\projects\projectA\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (D:\projects\projectA\node_modules\hardhat\src\builtin-tasks\compile.ts:1316:63)
    at async Environment._runTaskDefinition (D:\projects\projectA\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at async Environment.run (D:\projects\projectA\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (D:\projects\projectA\node_modules\hardhat\src\builtin-tasks\compile.ts:1383:7)
```

These are my dependencies
```
    "@nomiclabs/hardhat-ethers": "^2.0.0",
    "@nomiclabs/hardhat-etherscan": "^2.1.6",
    "@nomiclabs/hardhat-waffle": "^2.0.0",
    "@typechain/ethers-v5": "^2.0.0",
    "@typechain/hardhat": "^2.3.0",
    "@types/chai": "^4.2.21",
    "@types/mocha": "^9.0.0",
    "@types/node": "^16.9.1",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.0.0",
    "ethers": "^5.0.0",
    "hardhat": "^2.6.4",
    "ts-node": "^10.2.1",
    "typechain": "^3.0.0",
    "typescript": "^4.4.3"
```

**Comment by krzkaczor** [comment]
Please update all typechain releated packages to the newest version. Core package is way outdated

**Comment by reilgun** [comment]
> 
> 
> Please update all typechain releated packages to the newest version. Core package is way outdated

You're right. Though, I don't get why. Even if I delete all packages, clean cache, then install them all at once it seems to always pick typechain 3.0.0
I also got a peer dependency issue the first time I installed it

**Comment by krzkaczor** [comment]
just specify latest version in package.json. I am not sure maybe some other package (waffle) forces old typechain version...

**Comment by reilgun** [comment]
> just specify latest version in package.json. I am not sure maybe some other package (waffle) forces old typechain version...

Yes. Waffle seems to be the issue. I reinstalled everything in a different order and did waffle last, and had no conflicts, and everything is latest now. Thanks for the help
