### ISSUE TITLE
ethers-v5 gives TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by aspiers** [dethcrypto/TypeChain#622]
I am seeing the following error after upgrading to typechain 7.0.0 and @typechain/ethers-v5 9.0.0:

```
Creating Typechain artifacts in directory types/contracts for target ethers-v5
An unexpected error occurred:

TypeError: Cannot read property 'map' of undefined
    at new Ethers (/home/adam/my-project/node_modules/@typechain/ethers-v5/src/index.ts:53:4)
    at TypeChain.findRealImpl (/home/adam/my-project/node_modules/typechain/src/TypeChain.ts:50:12)
    at new TypeChain (/home/adam/my-project/node_modules/typechain/src/TypeChain.ts:22:26)
    at OverriddenTaskDefinition._action (/home/adam/my-project/node_modules/@typechain/hardhat/src/index.ts:44:7)
    at async Environment._runTaskDefinition (/home/adam/my-project/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async OverriddenTaskDefinition._action (/home/adam/my-project/node_modules/hardhat-contract-sizer/tasks/compile.js:6:3)
    at async Environment._runTaskDefinition (/home/adam/my-project/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (/home/adam/my-project/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async main (/home/adam/my-project/node_modules/hardhat/src/internal/cli/cli.ts:203:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```

Adding debug reveals that `allFiles` is `undefined` in the `Ethers` constructor.

**Comment by aspiers** [comment]
Turns out I had an ancient @typechain/hardhat (1.0.1) - upgrading to 4.0.0 fixed it.
