### ISSUE TITLE
Incompatible with hardhat-exposed

### ISSUE THREAD

**Issue by frangio** [dethcrypto/TypeChain#691]
The TypeChain Hardhat plugin seems incompatible with [hardhat-exposed](https://github.com/frangio/hardhat-exposed). Using the instructions here I could reproduce the issue: https://github.com/frangio/hardhat-exposed/issues/9#issuecomment-1124249292

The stack trace points to TypeChain code so you may have a better idea of what's happening.

The relevant context is that hardhat-exposed writes contracts to a separate directory (by default `./contracts-exposed`), and compiles those using Hardhat.

```
Error: EEXIST: file already exists, mkdir 'hardhat-waffle-template/contracts-exposed/Test.sol'
    at Object.mkdirSync (node:fs:1334:3)
    at mkdirpNativeSync (hardhat-waffle-template/node_modules/typechain/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at mkdirpSync (hardhat-waffle-template/node_modules/typechain/node_modules/mkdirp/index.js:21:7)
    at hardhat-waffle-template/node_modules/typechain/src/typechain/io.ts:19:5
    at Array.forEach (<anonymous>)
    at processOutput (hardhat-waffle-template/node_modules/typechain/src/typechain/io.ts:17:13)
    at runTypeChain (hardhat-waffle-template/node_modules/typechain/src/typechain/runTypeChain.ts:53:4)
    at async SimpleTaskDefinition.action (hardhat-waffle-template/node_modules/@typechain/hardhat/src/index.ts:83:20)
    at async Environment._runTaskDefinition (hardhat-waffle-template/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (hardhat-waffle-template/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14) {
```

**Comment by toshiSat** [comment]
I'm getting this error without using hardhat-exposed

**Comment by ndavd** [comment]
No updates on this?
