### ISSUE TITLE
Error when all ABIs in a project are empty

### ISSUE THREAD

**Issue by LogvinovLeon** [dethcrypto/TypeChain#728]
TypeChain receives the paths, skips all empty ABIs getting an empty array and then later in `lowestCommonPath` makes an assumption that the files array is either one element, or non-empty: https://github.com/dethcrypto/TypeChain/blob/master/packages/typechain/src/utils/files/lowestCommonPath.ts#L3

I think we should just noop on that run, but definitely don't throw as it's perfectly valid.

```
TypeError: Cannot read properties of undefined (reading 'filter')
    at lowestCommonPath (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/typechain@8.0.0_typescript@4.7.3/node_modules/typechain/src/utils/files/lowestCommonPath.ts:5:2)
    at detectInputsRoot (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/typechain@8.0.0_typescript@4.7.3/node_modules/typechain/src/utils/files/detectInputsRoot.ts:8:2)
    at runTypeChain (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/typechain@8.0.0_typescript@4.7.3/node_modules/typechain/src/typechain/runTypeChain.ts:31:13)
    at SimpleTaskDefinition.action (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/@typechain+hardhat@6.0.0_mkhsy5nvod365boywluagiegbu/node_modules/@typechain/hardhat/src/index.ts:83:38)
    at Environment._runTaskDefinition (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/hardhat@2.9.7_chai@4.3.6/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:35)
    at Environment.run (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/hardhat@2.9.7_chai@4.3.6/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:25)
    at OverriddenTaskDefinition._action (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/@typechain+hardhat@6.0.0_mkhsy5nvod365boywluagiegbu/node_modules/@typechain/hardhat/src/index.ts:31:11)
    at async Environment._runTaskDefinition (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/hardhat@2.9.7_chai@4.3.6/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/hardhat@2.9.7_chai@4.3.6/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/Users/leonidlogvinov/deth/dp2/node_modules/.pnpm/hardhat@2.9.7_chai@4.3.6/node_modules/hardhat/src/builtin-tasks/compile.ts:1358:63)
```

**Comment by krzkaczor** [comment]
Releated? https://github.com/dethcrypto/TypeChain/issues/717
